# permissions for end users to edit sagafinders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sagafinder-editor-role
rules:
- apiGroups:
  - event-finder.example.org
  resources:
  - sagafinders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - event-finder.example.org
  resources:
  - sagafinders/status
  verbs:
  - get
